# Generated by Django 4.1.10 on 2023-08-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.AddField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='a1.book'),
            preserve_default=False,
        ),
    ]
