# Generated by Django 4.1.10 on 2023-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_remove_sale_name_sale_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='number_of_sales',
            new_name='sales',
        ),
        migrations.AddField(
            model_name='review',
            name='number_of_down_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
