# Generated by Django 4.1.10 on 2023-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_rename_number_of_sales_sale_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='number_of_down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='number_of_up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
